### ISSUE TITLE
Search stats gives 0 for totalCount

### ISSUE THREAD

**Issue by tjsharp1** [ravendb/ravendb#17668] opened 2023-11-07 21:30 UTC
Doing a document search in dotnet is returning 0 for totalCount, when the same query in nodejs returns the correct document count.

I have the following code:
```
        var args = context.GetOptionalValidatedArgument<JobsQueryArguments>("query");

        using var session = scope.ServiceProvider.GetRequiredService<IAsyncDocumentSession>();

        var query = session
            .Advanced.AsyncDocumentQuery<JobIndex.Result, JobIndex>()
            .Search(args, out var stats);
```

This does return the documents that satisfy the query argument, but the total count returned in `stats` is still 0.

**Comment by ppekrol** [comment] 2023-11-08 08:16
Hi there,

I do not think that `.Search(args, out var stats)` method is from our API. You would have to check from where it is and what is the implementation there.

Usually in our API to achieve this, you have to do:
```
        var query = session
            .Advanced.AsyncDocumentQuery<JobIndex.Result, JobIndex>()
            .Statistics(out var stats);
            .Search(...);
```

**Comment by tjsharp1** [comment] 2023-11-08 22:56
yeah, I've tried this both ways. They give the same results, even though the same query works in nodejs.

**Comment by ppekrol** [comment] 2023-11-09 08:04
Can you create a failing test maybe? https://ravendb.net/docs/article-page/6.0/csharp/start/test-driver
I've tried reproducing this without any luck.

What Client API & Server version are you using?

**Comment by ppekrol** [comment] 2023-11-09 08:08
Hmm,

We have made a fix that will be in 6.0.1 that might be related to your scenario: https://github.com/ravendb/ravendb/pull/17486

Can you try installing latest 6.0.1 nightly Client API from here https://myget.org/feed/ravendb/package/nuget/RavenDB.Client ?

**Comment by georgiosd** [comment] 2023-11-18 14:22
Hey @ppekrol - we're still on 5.4.103 - did this bug affect the 5.x tree also?

**Comment by georgiosd** [comment] 2023-11-18 15:13
After investigating the issue further, it seems that `LongTotalResults = 0` when in fact `TotalResults = 4` (in my particular query).

I would have expected the two to be equal?

**Comment by grisha-kotler** [comment] 2023-11-20 09:38
@georgiosd Can you share the database and the query?

**Comment by georgiosd** [comment] 2023-11-22 18:52
@grisha-kotler sent a db and query from traffic watch to support@ravendb.net - seems to be an interaction with facets (query + facets, lazy). It works ok if I remove the facets.

**Comment by grisha-kotler** [comment] 2023-11-29 08:02
@georgiosd the issue is fixed [here](https://github.com/ravendb/ravendb/pull/17779)

**Closed as completed** 2024-04-22 10:35 UTC
