### ISSUE TITLE
Optimistic concurrency allows Fractured Read

### ISSUE THREAD

**Issue by aphyr** [ravendb/ravendb#17929] opened 2023-12-29 20:26 UTC
Building on #17927, it appears that transactions executed with optimistic concurrency allow G-single: read skew. Here's [an example test run](https://s3.amazonaws.com/jepsen.io/analyses/ravendb-6.0.4/20231229T140050.249-0600.zip): in five minutes it recorded hundreds of instances of G-single, G-nonadjacent, and G2-item. These anomalies are prohibited under Serializability, Snapshot Isolation, Repeatable Read, and Consistent View. For instance, here's a G-single case involving a read-write / write-write cycle between two transactions:

![Screenshot from 2023-12-29 14-14-58](https://github.com/ravendb/ravendb/assets/3748/9cc5d85d-f550-4a91-873b-069423f5b87e)

The top transaction, T1, read key 1060 and saw its value was `[2]`. It went on to append 5 and 6 to key 1093. The bottom transaction, T2, appended 3 to key 1060; from the read of `[2]`, we know that T2's first append must have executed *after* T1's first read. T2 went on to append 3 to key 1093, and then read key 1093's state as `[3]`--which tells us that T2 performed the first write to key 1093. From this we know that T1 must have appended 5 to key 1093 *after* T2 appended 3.

Here's a fractured read, in which top transaction T1 appends a value to keys 271 and 279, and bottom transaction T2 observes the write to 279 but *not* 271. This is forbidden under Read Atomic, and by extension Update Atomic, Causal, Prefix, Parallel Snapshot Isolation, and generalized SI.

![Screenshot from 2023-12-29 14-22-38](https://github.com/ravendb/ravendb/assets/3748/fed91826-8b36-42ce-accb-3d53452ea1c6)

**Comment by ayende** [comment] 2023-12-31 10:25
This is essentially a duplicate of https://github.com/ravendb/ravendb/issues/17928, given that I believe they have the same root cause. Full answer is there.

**Closed as completed by ayende** 2023-12-31 10:25 UTC

**Comment by arekpalinski** [comment] 2024-02-28 11:06
We have updated our documentation and provided more clarifications when talking about transactions in RavenDB and the Client API Session. 

The actual changes we made can be reviewed here: https://github.com/ravendb/docs/pull/1766.
