### ISSUE TITLE
RavenDB with dynamic OID for databases

### ISSUE THREAD

**Issue by mkocaks** [ravendb/ravendb#16574] opened 2023-05-31 09:45 UTC
Hi,
After a few days of researching it seems it may not be possible for the following with snmp exporter for prometheus.
We are looking to monitor our RavenDB Cluster and all metrics via SNMP using SNMP Exporter with Prometheus, however the way RavenDB references the databases is problematic!
For each database the OID is different and we would rather not statically define in snmp.yaml each OID for each database (that can change in future if we remove and/or add databases to the raven cluster)
https://github.com/ravendb/ravendb/blob/v5.4/src/Raven.Server/Monitoring/Snmp/SnmpOids.cs

i.e,
[Description("Database name")]
public const string Name = "5.2.{0}.1.1

Is there a way we can dynamically walk through each unknown oid off the parent oid and get each database metrics with snmp exporter or is our only option to statically define these out of band and keep updating the snmp config each time 

It seems the SNMP implementation is really focused around Zabbix and Zabbix has extended logic to deal with such situations however SNMP Exporter/Prometheus does not ideally would need confirmation if its possible or not (not being that we have to statically define each and every custom database OID in the snmp exporter Yaml config)

**Comment by ayende** [comment] 2023-06-07 10:59
duplicate of https://github.com/ravendb/ravendb/discussions/16573

**Closed as completed by ayende** 2023-06-07 10:59 UTC
