### ISSUE TITLE
Raven.Client.Exceptions.RavenException: System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by zakstam** [ravendb/ravendb#18043] opened 2024-01-26 09:40 UTC
I recently switched from Lucene to Corax and I started getting these errors:
```CSharp
  An unhandled exception has occurred while executing the request.
      Raven.Client.Exceptions.RavenException: System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at Corax.Querying.IndexSearcher.<SearchQuery>g__GetTermType|83_1(ReadOnlySpan`1 termValue) in D:\Builds\RavenDB-Stable-6.0\60008\src\Corax\Querying\IndexSearcher.Search.cs:line 132
         at Corax.Querying.IndexSearcher.SearchQuery(FieldMetadata field, IEnumerable`1 values, Operator operator, CancellationToken& cancellationToken) in D:\Builds\RavenDB-Stable-6.0\60008\src\Corax\Querying\IndexSearcher.Search.cs:line 127
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.HandleSearch(Parameters builderParameters, MethodExpression expression, Nullable`1 proximity)
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.ToCoraxQuery(Parameters builderParameters, QueryExpression expression, StreamingOptimization& leftOnlyOptimization, Boolean exact, Nullable`1 proximity) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 576
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.ToCoraxQuery(Parameters builderParameters, QueryExpression expression, StreamingOptimization& leftOnlyOptimization, Boolean exact, Nullable`1 proximity) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 576
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.BuildQuery(Parameters builderParameters, OrderMetadata[]& sortMetadata) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 283
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.QueryInternal[THighlighting,TQueryFilter,THasProjection,TDistinct](IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, Reference`1 scannedDocuments, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexReadOperation.cs:line 832
         at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Index.cs:line 3545
         at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Index.cs:line 3545
         at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Index.cs:line 3292
         at Raven.Server.Documents.Queries.Dynamic.DynamicQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Queries\Dynamic\DynamicQueryRunner.cs:line 69
         at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 99
         at Raven.Server.Documents.Handlers.Processors.Queries.DatabaseQueriesHandlerProcessorForGet.GetQueryResultsAsync(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, Boolean metadataOnly, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Handlers\Processors\Queries\DatabaseQueriesHandlerProcessorForGet.cs:line 53
         at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.ExecuteAsync() in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 219
         at Raven.Server.Documents.Handlers.QueriesHandler.Post() in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 15
         at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Routing\RequestRouter.cs:line 394
         at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\RavenServerStartup.cs:line 254
       ---> System.IndexOutOfRangeException: System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at Corax.Querying.IndexSearcher.<SearchQuery>g__GetTermType|83_1(ReadOnlySpan`1 termValue) in D:\Builds\RavenDB-Stable-6.0\60008\src\Corax\Querying\IndexSearcher.Search.cs:line 132
         at Corax.Querying.IndexSearcher.SearchQuery(FieldMetadata field, IEnumerable`1 values, Operator operator, CancellationToken& cancellationToken) in D:\Builds\RavenDB-Stable-6.0\60008\src\Corax\Querying\IndexSearcher.Search.cs:line 127
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.HandleSearch(Parameters builderParameters, MethodExpression expression, Nullable`1 proximity)
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.ToCoraxQuery(Parameters builderParameters, QueryExpression expression, StreamingOptimization& leftOnlyOptimization, Boolean exact, Nullable`1 proximity) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 576
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.ToCoraxQuery(Parameters builderParameters, QueryExpression expression, StreamingOptimization& leftOnlyOptimization, Boolean exact, Nullable`1 proximity) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 576
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.BuildQuery(Parameters builderParameters, OrderMetadata[]& sortMetadata) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 283
         at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.QueryInternal[THighlighting,TQueryFilter,THasProjection,TDistinct](IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, Reference`1 scannedDocuments, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexReadOperation.cs:line 832
         at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Index.cs:line 3545
         at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Index.cs:line 3545
         at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Indexes\Index.cs:line 3292
         at Raven.Server.Documents.Queries.Dynamic.DynamicQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Queries\Dynamic\DynamicQueryRunner.cs:line 69
         at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 99
         at Raven.Server.Documents.Handlers.Processors.Queries.DatabaseQueriesHandlerProcessorForGet.GetQueryResultsAsync(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, Boolean metadataOnly, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Handlers\Processors\Queries\DatabaseQueriesHandlerProcessorForGet.cs:line 53
         at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.ExecuteAsync() in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 219
         at Raven.Server.Documents.Handlers.QueriesHandler.Post() in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 15
         at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\Routing\RequestRouter.cs:line 394
         at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Server\RavenServerStartup.cs:line 254
         --- End of inner exception stack trace ---
         at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 114
         at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 118
         at Raven.Client.Http.Behaviors.DefaultCommandResponseBehavior.TryHandleUnsuccessfulResponseAsync[TResult](JsonOperationContext context, RavenCommand`1 command, HttpResponseMessage response) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Http\Behaviors\DefaultCommandResponseBehavior.cs:line 52
         at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Http\RequestExecutor.cs:line 1639
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Http\RequestExecutor.cs:line 1018
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Http\RequestExecutor.cs:line 1043
         at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteActualQueryAsync(CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1000
         at Raven.Client.Documents.Session.AsyncDocumentQuery`1.InitAsync(CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 990
         at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteQueryOperationInternal(Nullable`1 take, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 945
         at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteQueryOperation(Nullable`1 take, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 927
         at Features.Administrator.Customers.AdvancedSearchForCustomer.HandleAsync(AdvancedSearchForCustomerRequest req, CancellationToken ct) in C:\Backend\Features\Administrator\Customers\Queries\AdvancedSearchForCustomerEndpoint.cs:line 30     
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context)
         at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

My Query:
```CSharp
var session = _store.OpenAsyncSession();
var userList = await session.Query<Customer>()
    .Search(x => x.Info.Firstname, $"{req.FirstName}*")
    .Search(x => x.Info.Lastname, $"*{req.LastName}*", @operator: SearchOperator.Or)
    .Search(x => x.Info.Email, $"*{req.Email}*", @operator: SearchOperator.Or)
    .Take(30)
    .OrderByScore()
    .ThenBy(dto => dto.Id)
    .OfType<CustomerSearchDto>()
    // .Select(customer => new CustomerSearchDto
    // {
    //     Credentials = { Username = customer.Credentials.Username }
    // })
    .ToListAsync(ct);
```

Things I have tried:
- Reseting the index
- Deleting the index
- Manually creating the index instead of auto-generated

Running the query from RQL seems to work which means that either my C# query is wrong (although it has worked so far) or this is a client side bug.

RQL Query:
```CSharp
from index 'Auto/Customers/ByCredentials.UsernameAndSearch(Info.Email)AndSearch(Info.Firstname)AndSearch(Info.Lastname)'
where (search(Info.Email, "*zak*") or search(Info.Firstname, "", or) or search(Info.Lastname, "", or))
```

Custom index:
```CSharp
public class Advanced_Search_Customer : AbstractIndexCreationTask<Customer>
{
    public Advanced_Search_Customer()
    {
        Map = customers => from customer in customers
            select new
            {
                Firstname = customer.Info.Firstname,
                Lastname = customer.Info.Lastname,
                Email = customer.Info.Email
            };
        
        Indexes.Add(x => x.Info.Firstname, FieldIndexing.Search);
        Indexes.Add(x => x.Info.Lastname, FieldIndexing.Search);
        Indexes.Add(x => x.Info.Email, FieldIndexing.Search);
    }
}
```

**Comment by ayende** [comment] 2024-01-26 09:46
That looks like a bug in our code, can you show the `ToString()` on the query?
Can you send us a way to reproduce this?

**Comment by zakstam** [comment] 2024-01-26 09:56
I'm not sure if that is what you are asking for:
```CSharp
var query = session.Query<Customer>()
    .Search(x => x.Info.Firstname, $"{req.FirstName}*")
    .Search(x => x.Info.Lastname, $"*{req.LastName}*", @operator: SearchOperator.Or)
    .Search(x => x.Info.Email, $"*{req.Email}*", @operator: SearchOperator.Or)
    .Take(30)
    .OrderByScore()
    .ThenBy(dto => dto.Id)
    .OfType<CustomerSearchDto>();


var str = query.ToString();
var userList = await query.ToListAsync(ct);
```

str = `from 'Customers' where (search(Info.Firstname, $p0) or search(Info.Lastname, $p1) or search(Info.Email, $p2)) order by score(), id() limit $p3, $p4`

**Comment by ayende** [comment] 2024-01-26 10:00
Yes, that is great. Can you also look at the traffic watch when you run this query and send it?

**Comment by zakstam** [comment] 2024-01-26 10:00
Running the same query in RQL seems to work:
```CSharp
from "Customers" 
where (search(Info.Email, "*zak*") or search(Info.Firstname, "", or) or search(Info.Lastname, "", or)) 
order by score()
limit 30
```

**Comment by ayende** [comment] 2024-01-26 10:02
I assume that this is related to parameter parsing in Corax.
Go to this page (on your server)
http://live-test.ravendb.net/studio/index.html#admin/settings/trafficWatch

And then run the query causing the issue, then send us the results please

**Comment by zakstam** [comment] 2024-01-26 10:05
There is an error when i inspect the traffic and it is replicable. It seems that if the query contains empty string but also contains "*" the query fails. 
```
from 'Customers' where (search(Info.Firstname, $p0) or search(Info.Lastname, $p1) or search(Info.Email, $p2)) order by score(), id() limit $p3, $p4
{"p0":"*","p1":"**","p2":"*zaaksssass*","p3":0,"p4":30}
```

**Comment by zakstam** [comment] 2024-01-26 10:05
If i add some characters inside p0 and p1 it works

**Comment by zakstam** [comment] 2024-01-26 10:07
I will fix this by conditionally building the search parameters for now and remove the asterisks if the parameter is empty but I assume this is something you are going to fix

**Comment by ayende** [comment] 2024-01-26 10:07
Confirmed, that is a bug on our end. We'll be fixing that

**Comment by zakstam** [comment] 2024-01-26 10:09
This works:

```CSharp
  var firstName = string.IsNullOrEmpty(req.FirstName) ? string.Empty : $"{req.FirstName}*";
  var lastName = string.IsNullOrEmpty(req.LastName) ? string.Empty : $"*{req.LastName}*";
  var email = string.IsNullOrEmpty(req.Email) ? string.Empty : $"*{req.Email}*";
  var query = session.Query<Customer>()
      .Search(x => x.Info.Firstname, firstName)
      .Search(x => x.Info.Lastname, lastName, @operator: SearchOperator.Or)
      .Search(x => x.Info.Email, email, @operator: SearchOperator.Or)
      .Take(30)
      .OrderByScore()
      .ThenBy(dto => dto.Id)
      .OfType<CustomerSearchDto>();
```

**Comment by zakstam** [comment] 2024-01-26 10:39
Also @ayende , it seems to be returning results even when there are none. For example:
```
from 'Customers' where (search(Info.Firstname, $p0) or search(Info.Lastname, $p1) or search(Info.Email, $p2)) order by score(), id() limit $p3, $p4
{"p0":"","p1":"","p2":"*SomeNonExistentEmail*","p3":0,"p4":30}
```

The above query returns 30 customers alphabetically ordered

**Comment by ayende** [comment] 2024-01-26 12:20
Fairly certain that you are trying to find `""` in the text and that may find everything.

**Comment by ayende** [comment] 2024-01-26 12:39
https://issues.hibernatingrhinos.com/issue/RavenDB-21995/Corax-query-using-searchEmail-throws

**Comment by zakstam** [comment] 2024-01-26 13:31
> Fairly certain that you are trying to find `""` in the text and that may find everything.


Fair assumption but i forgot to mention that my initial query was with SearchOperator.And instead of SearchOperator.Or.
```CSHarp
var firstName = string.IsNullOrEmpty(req.FirstName) ? string.Empty : $"{req.FirstName}*";
var lastName = string.IsNullOrEmpty(req.LastName) ? string.Empty : $"*{req.LastName}*";
var email = string.IsNullOrEmpty(req.Email) ? string.Empty : $"*{req.Email}*";
var query = session.Query<Customer>()
    .Search(x => x.Info.Firstname, firstName)
    .Search(x => x.Info.Lastname, lastName, @operator: SearchOperator.And)
    .Search(x => x.Info.Email, email, @operator: SearchOperator.And)
    .Take(30)
    .OrderByScore()
    .ThenBy(dto => dto.Id)
    .OfType<CustomerSearchDto>();
```

Assuming that only the email parameter has data, I would expect this to only return results that contain the email (or part of it). At least, this is how it has worked so far. Maybe the reason is because I'm using empty strings instead of "*"? If so, I will have to wait for the issue to be resolved and test again.

**Comment by ayende** [comment] 2024-01-26 14:45
Empty string should match everyting, IIRC. We are looking into this with more depth now

**Comment by zakstam** [comment] 2024-01-26 15:33
Our database died a few moments ago btw with an error `Fatal error. Internal CLR error. (0x80131506)`. I have switched back to Lucene for now since that is the only thing that was changed today that could have caused issues. I'm posting this here because I think it might be related. Also, I could not find anything useful about this in the event logs (its windows server) or the Logs folder of ravendb.

EDIT: I have also reset all the index back to Lucene

**Comment by maciejaszyk** [comment] 2024-01-26 15:42
@zaksnet 
did you push any documents in the meantime that could cause the crash during indexing, or did it crash during/after querying?

**Comment by zakstam** [comment] 2024-01-26 15:45
The database is being used in a production environment so both. Documents are being pushed (created, and updated) and the index is being queried

**Comment by maciejaszyk** [comment] 2024-01-26 15:51
After rebooting RavenDB, did it happen again, or did the index process documents without issues?

**Comment by zakstam** [comment] 2024-01-26 15:59
The server started properly and i didn't see any error but customers could not login (the documents related to the index are customer accounts). The dashboard was working properly though so I went into the database settings and changed the search engine to Lucene, restarted the server and everything seemed to work. One thing to note is that if I recall properly, it started working right away after I changed the engine to Lucene and restarted the server, even though some indexes were still using Corax. I did reset the indexes just in case

**Comment by maciejaszyk** [comment] 2024-01-26 16:11
Do you also use AutoIndexes? It seems like DB automatically rebuild the index.

FYI, changing the search engine in settings will alter the default search engine for new indexes. Existing indexes must be manually reset to change the engine.

**Comment by zakstam** [comment] 2024-01-26 16:14
All of the indexes are automatically generated, I am not manually creating any indexes. 

Exactly, that is why I reset the indexes, to get them back to Lucene.

**Comment by arekpalinski** [comment] 2024-01-31 07:55
Fixed in https://github.com/ravendb/ravendb/pull/18064

**Closed as completed by arekpalinski** 2024-01-31 07:55 UTC
