### ISSUE TITLE
Collections with 0 entries still occupy significant space

### ISSUE THREAD

**Issue by korkmazozcan** [ravendb/ravendb#12748] opened 2021-09-10 15:21 UTC
When all documents are deleted in a collection, collection(table tree) itself is never deleted and occupies around 15 MB space.

![image](https://user-images.githubusercontent.com/17751620/132874872-5d3c785b-7ead-4b10-93e2-79786692533d.png)
![image](https://user-images.githubusercontent.com/17751620/132875701-28060466-5f17-4714-9b4c-e95aff9995e8.png)
![image](https://user-images.githubusercontent.com/17751620/132875838-f692bac5-cb61-47cd-acac-4eaf42249ff1.png)
![image](https://user-images.githubusercontent.com/17751620/132875950-f2b00087-b900-431d-acec-cda5d09088a3.png)
![image](https://user-images.githubusercontent.com/17751620/132876065-01ed2844-b72d-4bee-a228-0d44843b5ec7.png)

Our application retrieves raw data from external APIs, persists to RavenDb, after generating summary documents using raw data, deletes all raw data.

For 100 operations, we generate 100 MB of summary data with 1500 MB undeletable collection data of deleted raw data.

Is there a way to clean these unnecessary table tree data?

P.S: 
1. There is an unresolved issue back from 2019 on youtrack: [https://issues.hibernatingrhinos.com/issue/RavenDB-13801](https://issues.hibernatingrhinos.com/issue/RavenDB-13801)
2. I tried "compact database" option, but it didn't help, still 15 MB permanent foot-print for a one time used collection.

**Comment by ayende** [comment] 2021-09-12 07:21
That is a known issue, yes. We don't really consider the scenario of temporary collections.
Is there a reason why you are creating things in this manner?
The issue is related to performance, we don't want to keep allocation / deallocation on every time that you create / remove a single collection.

And providing an API for deleting a collection directly isn't ideal either, for other reasons.

The common approach is to use known collection names. If you need to make them temporary, you can use an id prefix, which also usually make it easier to work with.

**Comment by korkmazozcan** [comment] 2021-09-23 07:03
> The issue is related to performance, we don't want to keep allocation / deallocation on every time that you create / remove a single collection.

You are right about allocation/deallocation design decisions. 

>Is there a reason why you are creating things in this manner?

We are evaluating ravendb as a calculation hub with a workflow like: 
- pull data from various APIs
- BulkInsert pulled raw data(>2 GB) to ravendb,
- run calculations on ravendb as patchbyquery operations
- output as one document with many timeseries(< 5 MB) 
- delete raw data

>The common approach is to use known collection names. If you need to make them temporary, you can use an id prefix, which also usually make it easier to work with.

We benchmarked various approaches including the one you mentioned. We ended up: 
- create a temp DB to store raw data, 
- execute patchbyquery operations and generate a document with many timeseries,
- move output document to main db
- delete newly created temp db and files

@ayende : You may close this issue, if our approach is suitable. Thanks.

**Comment by ayende** [comment] 2021-09-23 12:05
Yes, that can work. Closing the issue, then.

**Closed as completed by ayende** 2021-09-23 12:05 UTC
