### ISSUE TITLE
Potential thread starvation problem with SyncOverAsync in aggressive caching

### ISSUE THREAD

**Issue by danielmarbach** [ravendb/ravendb#15378] opened 2022-12-02 15:05 UTC
I'm trying to get to the bottom of an issue a client is facing. It appears there is a SSL connection issue in their environment (potentially with an invalid certificate?).

![image](https://user-images.githubusercontent.com/174258/205321268-272a0de7-7211-4167-8e58-fe0847586563.png)

When this happens our code that tries to run a query against a collection starts starving very rapidly.

![image](https://user-images.githubusercontent.com/174258/205321541-94ba93db-63a6-4bab-b0fe-e668b56c171c.png)

https://github.com/Particular/NServiceBus.RavenDB/blob/release-7.1/src/NServiceBus.RavenDB/Subscriptions/SubscriptionPersister.cs#L124

This seems to come from

```csharp
private void ListenToChangesAndUpdateTheCache(string database)
        {
            Debug.Assert(database != null);

            if (_aggressiveCacheChanges.TryGetValue(database, out var lazy) == false)
            {
                lazy = _aggressiveCacheChanges.GetOrAdd(database, new Lazy<EvictItemsFromCacheBasedOnChanges>(
                    () => new EvictItemsFromCacheBasedOnChanges(this, database)));
            }
            GC.KeepAlive(lazy.Value); // here we force it to be evaluated
            lazy.Value.EnsureConnected();
        }
```

specifically from

```csharp
lazy.Value.EnsureConnected();
```

which does sync over async

```csharp
        public void EnsureConnected()
        {
            AsyncHelpers.RunSync(_changes.EnsureConnectedNow);
        }
```

https://github.com/ravendb/ravendb/blob/5a1294432f77cb456b5a123b3c118b0e2fbf4ce4/src/Raven.Client/Documents/Changes/EvictItemsFromCacheBasedOnChanges.cs#L35

Note the calling code that the client has in place also uses quite a few synchronous APIs on the synchronous document session which I think are also doing sync over async. Eventually, things start to stall rapidly.

I will figure out what's going on with the certificate but I wanted to raise this here to trigger awareness and maybe you can spot something in the interaction with the AsyncHelper that could cause this.

**Comment by ayende** [comment] 2022-12-04 08:56
That is a bug, yes. The problem is that we have to ensure that the channel is connected before we continue.
I think that the only proper way to actually handle that would be to add `AggressivelyCacheForAync`, which isn't ideal.

**Comment by ayende** [comment] 2022-12-04 08:56
https://issues.hibernatingrhinos.com/issue/RavenDB-19608/Add-AggressivelyCacheForAync-to-avoid-sync-usage-in-async-manner

**Comment by ayende** [comment] 2022-12-04 09:03
As a workaround, `DoNotTrack` aggressive caching may help here? If you don't need the server notifications

**Comment by danielmarbach** [comment] 2022-12-04 09:09
Thanks Oren! I will look into this Monday and report back

I do think though we need the notifications for the cases when new subscribers are added during the runtime

**Comment by danielmarbach** [comment] 2022-12-04 14:55
@ayende weekend mode so I might be totally overseeing a lot here. But why not move the cache scope into the document session? Then you already know whether you deal with sync or async.

**Comment by ayende** [comment] 2022-12-05 06:52
Aggressive cache is set _across_ sessions.
That's the problem.

**Comment by ayende** [comment] 2022-12-05 06:53
We *may* be able to do that by adding a _pre-req_ task that we'll wait on at the doc store level, I guess.
That would avoid the API change.

**Comment by danielmarbach** [comment] 2022-12-05 07:58
> Aggressive cache is set _across_ sessions. That's the problem.

Ah yeah I forgot that.

**Comment by ayende** [comment] 2022-12-11 08:29
https://github.com/ravendb/ravendb/pull/15417

**Comment by danielmarbach** [comment] 2023-01-12 11:12
This can be closed right?

**Comment by danielmarbach** [comment] 2023-01-12 11:12
Any reasons why this has only been introduced into 5.4 and not the other supported versions of the client?

As it stands right now we would have to bump the minim required version of the client to fix our code

https://github.com/Particular/NServiceBus.RavenDB/pull/1091/files#diff-fb4679b86aebe84e8da111ad7aa1896b41c220a9bc89994b8f1b06c2c25fa632R18

**Comment by ppekrol** [comment] 2023-01-13 14:51
> Any reasons why this has only been introduced into 5.4 and not the other supported versions of the client?
> 
> As it stands right now we would have to bump the minim required version of the client to fix our code
> 
> https://github.com/Particular/NServiceBus.RavenDB/pull/1091/files#diff-fb4679b86aebe84e8da111ad7aa1896b41c220a9bc89994b8f1b06c2c25fa632R18

Hi, the 5.2 is out of enhancements period and we are slowly moving it into EOL state (July 2023) considering only low risk or critical items there.

**Closed as completed by ppekrol** 2023-01-13 14:51 UTC

**Comment by danielmarbach** [comment] 2023-01-13 15:05
@ppekrol so thread starvation problems are not considered critical?

**Comment by ppekrol** [comment] 2023-01-13 15:21
1. There is possible, less convenient, workaround with 'DoNotTrack' option IIRC
2. We would suggest upgrading to 5.4 client due to 5.2 reaching EOL soon
