### ISSUE TITLE
Quotes in search does not do an exact match of the phrase

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#16689] opened 2023-06-16 21:31 UTC
RavenDB search - when we perform a quoted search like "red green" it returns the results with "red green" and also with "red and green". I dont seem to understand why it includes the stop word and. We dont want that in the result set. 

Any way to limit and make it do an exact match of the quoted search keyword? 

We are using Standard analyzer and the Indexing type is Search. 

![image](https://github.com/ravendb/ravendb/assets/133284420/48b2a5c1-c5c6-4e96-b7ba-945401d74d7f)

**Comment by ayende** [comment] 2023-06-18 09:14
duplicate of https://github.com/ravendb/ravendb/discussions/16688

**Closed as completed by ayende** 2023-06-18 09:14 UTC
